# Generated by Django 4.2.4 on 2023-08-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='sur_name',
        ),
    ]
